import { Ionicons } from '@expo/vector-icons';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '@/src/auth/AuthProvider';
import { ROLE_LABELS } from '@/src/types/auth';
import { colors } from '@/src/theme/colors';

const perms = { super_admin:['All platform access','User and role management','Incident control','System configuration'], operations_manager:['Command Center','Operations','Incident control','Reports'], dispatcher:['Orders & Dispatch','Logistics','Acknowledge / resolve incidents'], analyst:['Command Center','Analytics','Read-only operations'], viewer:['Command Center','Read-only monitoring'] } as const;
export default function MoreScreen(){ const {session,signOut}=useAuth(); if(!session)return null; const role=session.user.role; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{session.user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</Text></View><Text style={styles.name}>{session.user.name}</Text><Text style={styles.email}>{session.user.email}</Text><View style={styles.role}><Ionicons name="shield-checkmark" size={15} color={colors.purple600}/><Text style={styles.roleText}>{ROLE_LABELS[role]}</Text></View></View><Text style={styles.heading}>ACCESS & RBAC</Text><View style={styles.card}>{perms[role].map((p,i)=><View key={p} style={[styles.row,i>0&&styles.rowBorder]}><Ionicons name="checkmark-circle" size={16} color={colors.success}/><Text style={styles.rowText}>{p}</Text></View>)}</View><Text style={styles.heading}>ORGANIZATION</Text><View style={styles.card}><Text style={styles.orgName}>Cushy Access</Text><Text style={styles.orgSub}>Nexus organization workspace</Text><View style={styles.orgId}><Text style={styles.orgIdText}>org-cushy</Text></View></View><Pressable onPress={()=>Alert.alert('Sign out','Sign out of Cushy Access Nexus?', [{text:'Cancel',style:'cancel'},{text:'Sign out',style:'destructive',onPress:()=>void signOut()}])} style={styles.signout}><Ionicons name="log-out-outline" size={18} color={colors.danger}/><Text style={styles.signoutText}>Sign out</Text></Pressable></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.canvas},content:{padding:16,paddingBottom:30},profile:{backgroundColor:colors.purple900,borderRadius:22,padding:18,alignItems:'center'},avatar:{width:64,height:64,borderRadius:22,backgroundColor:colors.yellow,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:20,fontWeight:'900',color:colors.ink},name:{marginTop:11,color:colors.surface,fontSize:17,fontWeight:'900'},email:{marginTop:3,color:'#D7C6E8',fontSize:10},role:{marginTop:10,backgroundColor:colors.purple100,paddingHorizontal:10,paddingVertical:6,borderRadius:999,flexDirection:'row',gap:6,alignItems:'center'},roleText:{fontSize:9,fontWeight:'900',color:colors.purple600},heading:{marginTop:18,marginBottom:8,fontSize:9,fontWeight:'900',letterSpacing:1.2,color:colors.slate},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:17,paddingHorizontal:14},row:{paddingVertical:13,flexDirection:'row',gap:9,alignItems:'center'},rowBorder:{borderTopWidth:1,borderTopColor:colors.border},rowText:{fontSize:10,fontWeight:'700',color:colors.ink},orgName:{fontSize:15,fontWeight:'900',color:colors.ink,paddingTop:14},orgSub:{fontSize:10,color:colors.slate,marginTop:3},orgId:{alignSelf:'flex-start',marginTop:10,marginBottom:14,paddingHorizontal:8,paddingVertical:5,borderRadius:7,backgroundColor:colors.purple50},orgIdText:{fontSize:8,fontWeight:'900',color:colors.purple600},signout:{marginTop:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.dangerSoft,borderRadius:15,padding:13,flexDirection:'row',justifyContent:'center',gap:8},signoutText:{fontSize:10,fontWeight:'900',color:colors.danger}})
